version: '3.9'

services:

  # ── BASE DE DONNÉES MySQL ────────────────────────
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ularavel_user", "-plaravel_pass"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3308:3306"
    networks:
      - app_network

  # ── BACKEND LARAVEL ──────────────────────────────
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_api
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: ""
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_pass
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8000"
    networks:
      - app_network
    restart: unless-stopped

  # ── FRONTEND ANGULAR ─────────────────────────────
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

  # ── PROMETHEUS ───────────────────────────────────
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app_network

  # ── GRAFANA ──────────────────────────────────────
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
  grafana_data: